# verify_socle.sage -- independent verification of the socle / Cohen-Macaulay type
# of the Dirichlet truncations Gamma_n = S/I_n.
#
# Changelog (reverse-chronological):
#   2026-08-27 07:03 - Claude: RES_MAX lowered 40 -> 30 after Singular's mres blew
#     past 5.8 GB RSS somewhere in n = 31..40 on the first run; added PART 5 (socle
#     degrees / levelness); replaced all f-strings with %-formatting, because Sage's
#     preparser rewrites numeric literals inside nested string literals in f-strings
#     and printed a header column as "ceil(n/_sage_const_2 )".
#   2026-08-27 06:40 - Claude: created. Verifies, along a route independent of the
#     elementary count in code/socle_and_macaulay_check.py:
#       (a) dim_K Gamma_n = n                     [sanity: the ideal really is I_n]
#       (b) dim_K socle(Gamma_n) = ceil(n/2)      [via Singular ideal quotient (I:m)]
#       (c) beta_r^S(Gamma_n)   = ceil(n/2)       [via Singular minimal free resolution]
#       (d) socle monomials = { m : n/2 < w(m) <= n }
#       (e) the bijection m <-> x_1*m onto { u in G(I_n) : min(u) = 1 }, i.e.
#           dim socle = C_{n,1}, computed from Singular's minbase, not from Phi(n,2)
#       (f) beta_i^S(Gamma_n) = sum_v C_{n,v} binom(r-v, i-1)   [reversed Eliahou-Kervaire]
#       (g) Gorenstein  <=>  n <= 2, cross-checked against C_n = mu(I_n)
#       (h) socle degrees by Omega: level exactly for n <= 3
#
#     The ideal is deliberately built WITHOUT using the minimal-generator
#     characterisation: I_n is generated by *all* monomials of weight in
#     (n, n*p_r], a superset of G(I_n) (every minimal generator u satisfies
#     w(u) = lpf(w(u)) * w(u/x_lpf) <= p_r * n), and Singular interreduces.
#
#     Ranges reached: socle-by-ideal-quotient n <= 120; free resolution n <= 30.
#     Runtime a few minutes.  Raw output: runs/REPORT-socle.txt.

import sys
from sage.libs.singular.function import singular_function

minbase = singular_function('minbase')


def smooth_ints(lo, hi, pr):
    """Integers W with lo < W <= hi all of whose prime factors are <= pr."""
    out = []
    for W in range(lo + 1, hi + 1):
        f = factor(W)
        if all(p <= pr for p, _ in f):
            out.append(W)
    return out


def exponent_vector(W, primes):
    return [W.valuation(p) for p in primes]


def build(n):
    """Return (S, I_n, primes)."""
    primes = list(primes_first_n(prime_pi(n)))
    r = len(primes)
    S = PolynomialRing(QQ, r, 'x')
    xs = S.gens()
    gens = []
    for W in smooth_ints(n, n * primes[-1], primes[-1]):
        e = exponent_vector(Integer(W), primes)
        gens.append(prod(xs[i] ** e[i] for i in range(r)))
    return S, S.ideal(gens), primes


def weight(mon, primes):
    return prod(p ** a for p, a in zip(primes, mon.exponents()[0]))


def betti_numbers(I):
    """Total Betti numbers beta_i^S(S/I) from Singular's minimal free resolution."""
    res = I.free_resolution()
    b = [Integer(res.differential(1).matrix().nrows())]
    for i in range(1, len(res) + 1):
        b.append(Integer(res.differential(i).matrix().ncols()))
    return b


def C_profile(I, primes):
    """C_{n,v} = # minimal generators with least variable index v, from minbase."""
    r = len(primes)
    C = [0] * (r + 1)
    for u in minbase(I):
        e = u.exponents()[0]
        v = min(i for i in range(r) if e[i] > 0) + 1
        C[v] += 1
    return C[1:]


def run(n, do_resolution=True):
    rec = {'n': n}
    if n == 1:
        # Degenerate: r = 0, S = K, I_1 = 0, Gamma_1 = K, m = 0, socle = K.
        rec.update(dim=1, socle=1, ceil=1, betti=[1], beta_last=1,
                   socle_mons=[1], Cn1=0, ek_ok=None, gorenstein=True,
                   note='degenerate: r=0, S=K, Gamma_1=K')
        return rec
    S, I, primes = build(n)
    r = len(primes)
    m = S.ideal(S.gens())
    dimA = I.vector_space_dimension()
    Q = I.quotient(m)
    socdim = dimA - Q.vector_space_dimension()

    # socle monomials: minimal generators of (I:m) that are not already in I
    socmons = sorted(weight(u, primes) for u in minbase(Q)
                     if u.reduce(I.groebner_basis()) != 0)

    C = C_profile(I, primes)
    rec.update(n=n, r=r, dim=dimA, socle=socdim, ceil=ceil(n / 2),
               socle_mons=socmons, Cn1=C[0], C=C,
               gorenstein=(socdim == 1))
    if do_resolution:
        b = betti_numbers(I)
        rec['betti'] = b
        rec['beta_last'] = b[-1]
        rec['pd'] = len(b) - 1
        rec['ek_ok'] = all(
            b[i] == sum(C[v - 1] * binomial(r - v, i - 1) for v in range(1, r + 1))
            for i in range(1, len(b)))
    return rec


def main():
    import sage.version
    print("=" * 78)
    print("Independent verification of socle(Gamma_n) and the Cohen-Macaulay type")
    print("SageMath " + sage.version.version + "  (Singular back end)")
    print("=" * 78)
    print()
    print("Ideal built from ALL monomials of weight in (n, n*p_r]; Singular")
    print("interreduces.  Socle via the ideal quotient (I_n : m); last Betti number")
    print("via Singular's minimal free resolution (mres).  Neither route uses the")
    print("elementary characterisation 2*w(m) > n.")
    print()

    # Free resolutions are the expensive route: minimal resolutions over a
    # polynomial ring in r(n) variables of an ideal with C_n generators.  A trial
    # run with RES_MAX = 40 was killed after Singular's mres passed 5.8 GB RSS
    # somewhere in 31..40; 30 completes comfortably.  The ideal-quotient route is
    # combinatorial and stays cheap much further out.
    RES_MAX = 30      # attempt free resolutions up to here
    QUO_MAX = 120     # ideal-quotient route up to here

    print("-" * 78)
    print("PART 1.  socle dimension, last Betti number, ceil(n/2)")
    print("-" * 78)
    print("%4s %3s %6s %6s %9s %7s %5s %6s %5s %6s" %
          ("n", "r", "dim_K", "socle", "ceil(n/2)", "beta_r", "pd_S",
           "C_n,1", "EK", "Gor"))
    ok = True
    for n in range(1, QUO_MAX + 1):
        rec = run(n, do_resolution=(n <= RES_MAX))
        checks = [rec["dim"] == n, rec["socle"] == rec["ceil"],
                  rec["socle"] == rec.get("Cn1", rec["socle"]) or n == 1]
        if "beta_last" in rec:
            checks += [rec["beta_last"] == rec["ceil"],
                       rec.get("pd", rec["n"]) == rec.get("r", 0) or n == 1,
                       rec["ek_ok"] in (True, None)]
        if not all(checks):
            ok = False
            print("   *** FAILED at n = %s: %s" % (n, rec))
        if n <= 30 or n % 10 == 0:
            print("%4s %3s %6s %6s %9s %7s %5s %6s %5s %6s%s" %
                  (n, rec.get("r", 0), rec["dim"], rec["socle"], rec["ceil"],
                   rec.get("beta_last", "-"), rec.get("pd", "-"),
                   rec.get("Cn1", "-"), rec.get("ek_ok", "-"),
                   rec["gorenstein"],
                   ("   <- " + rec["note"]) if "note" in rec else ""))
            sys.stdout.flush()
    print()
    print("All checks passed for n = 1 .. %s:  %s" % (QUO_MAX, ok))
    print("  (free resolution, pd and Eliahou-Kervaire columns computed for")
    print("   n <= %s; socle-by-ideal-quotient for all n <= %s.)" % (RES_MAX, QUO_MAX))
    print()

    print("-" * 78)
    print("PART 2.  socle monomials are exactly the integers in (n/2, n]")
    print("-" * 78)
    bad = []
    for n in range(2, QUO_MAX + 1):
        rec = run(n, do_resolution=False)
        expect = [Integer(w) for w in range((n // 2) + 1, n + 1)]
        got = [Integer(w) for w in rec["socle_mons"]]
        if got != expect:
            bad.append(n)
        if n <= 16:
            print("  n=%3s: socle monomials (as integers) = %s   expected %s" %
                  (n, got, expect))
        sys.stdout.flush()
    print("  mismatches over n = 2 .. %s: %s" % (QUO_MAX, bad if bad else "none"))
    print()

    print("-" * 78)
    print("PART 3.  the bijection  m <-> x_1*m  between socle monomials and")
    print("         minimal generators of least index 1")
    print("-" * 78)
    bad = []
    for n in range(2, RES_MAX + 1):
        S, I, primes = build(n)
        r = len(primes)
        mm = S.ideal(S.gens())
        Q = I.quotient(mm)
        G = I.groebner_basis()
        soc = [u for u in minbase(Q) if u.reduce(G) != 0]
        g1 = [u for u in minbase(I)
              if min(i for i in range(r) if u.exponents()[0][i] > 0) == 0]
        lhs = sorted(weight(S.gen(0) * u, primes) for u in soc)
        rhs = sorted(weight(u, primes) for u in g1)
        if lhs != rhs:
            bad.append(n)
        if n <= 12:
            print("  n=%3s: 2*(socle weights)           = %s" % (n, lhs))
            print("         weights of G(I) with min=1  = %s" % (rhs,))
        sys.stdout.flush()
    print("  mismatches over n = 2 .. %s: %s" % (RES_MAX, bad if bad else "none"))
    print()

    print("-" * 78)
    print("PART 4.  Gorenstein locus")
    print("-" * 78)
    for n in range(1, 13):
        rec = run(n, do_resolution=False)
        print("  n=%3s: type = %3s   Gorenstein: %s" %
              (n, rec["socle"], rec["gorenstein"]))
    print()
    print("  n=1: Gamma_1 = K (r=0). Trivially Gorenstein; degenerate, m = 0.")
    S, I, primes = build(2)
    print("  n=2: S = %s, minbase(I_2) = %s" % (S, minbase(I)))
    print("       so Gamma_2 = K[x]/(x^2), a hypersurface, hence a complete")
    print("       intersection, hence Gorenstein.")
    S, I, primes = build(3)
    print("  n=3: minbase(I_3) = %s, so Gamma_3 = K[x,y]/(x,y)^2, type 2." %
          (minbase(I),))
    print()
    print("  Cross-check independent of the socle count, via Avramov's remark")
    print("  after 5.2.5 in *Infinite free resolutions* (a Golod Gorenstein local")
    print("  ring is a hypersurface): Gamma_n is Golod for every n, so it is")
    print("  Gorenstein only if mu(I_n) = C_n <= 1.")
    for n in range(2, 16):
        S, I, primes = build(n)
        c = len(minbase(I))
        print("    n=%3s: mu(I_n) = C_n = %3s%s" %
              (n, c, "   (hypersurface)" if c == 1 else ""))
    print()
    print("-" * 78)
    print("PART 5.  socle degrees (grading by Omega): Gamma_n is level only for n <= 3")
    print("-" * 78)
    print("  A graded Artinian algebra is level when its socle sits in one degree.")
    print("  Socle degrees below are Omega(m) for m in the socle, from PART 2's")
    print("  machine-computed socle, not from the (n/2, n] description.")
    lev = []
    for n in range(2, QUO_MAX + 1):
        rec = run(n, do_resolution=False)
        degs = sorted(set(sum(e for _, e in factor(Integer(w)))
                          for w in rec["socle_mons"]))
        if len(degs) == 1:
            lev.append(n)
        if n <= 12:
            print("  n=%3s: socle = %s, degrees = %s%s" %
                  (n, rec["socle_mons"], degs, "   LEVEL" if len(degs) == 1 else ""))
        sys.stdout.flush()
    print("  level for n in 2 .. %s:  %s" % (QUO_MAX, lev))
    print()
    print("=" * 78)
    print("done")


main()
